SELECT TOP (1000) [Record_ID]
      ,[First_Name]
      ,[Last_Name]
      ,[Full_Name]
      ,[Age]
      ,[Gender]
      ,[Country]
      ,[Province]
      ,[South_African_ID]
      ,[Case_Number]
      ,[Crime_Type]
      ,[Financial_Score]
      ,[Estimated_Fraud_Amount_ZAR]
      ,[Risk_Level]
      ,[Case_Status]
      ,[Bank_Involved]
      ,[Previous_Offenses]
      ,[Arrested]
      ,[Crime_Date]
      ,[Court_Date]
      ,[Investigating_Officer]
      ,[Station_Code]
  FROM [Police_Case].[dbo].[South_African_Criminal_data]
